### ISSUE TITLE
Display:inline-block and whitespace in your html

### ISSUE THREAD

**Issue by tevko** [mdo/wtf-html-css#23] opened 2014-03-24 21:05 UTC
2 side by side elements at 50% width will not float next to each other unless there is no whitespace in the HTML http://codepen.io/tevko/pen/dsKjf/

**Comment by jbkkd** [comment] 2014-03-25 08:42
wtf, html

**Comment by klepas** [comment] 2014-03-25 14:12
Wat.

**Comment by tevko** [comment] 2014-03-25 14:37
This is an intended behavior (inline block is supposed to account for whitespace around it) but it seems antiquated as layout other than DOM order should be almost entirely up to css. It also makes for a lot of freaking out when your basic code isn't working

**Comment by danburzo** [comment] 2014-03-25 18:31
Also here: https://github.com/mdo/wtf-html-css/issues/1 :-)

**Comment by mdo** [comment] 2014-03-25 21:37
Closing as dupe of #1.

**Closed as completed by mdo** 2014-03-25 21:37 UTC
