### ISSUE TITLE
Spaces between inline-block elements affect layout

### ISSUE THREAD

**Issue by RonnyO** [mdo/wtf-html-css#34] opened 2014-03-28 11:59 UTC
Proper formatting of code uses spaces, and if you use inline-block for layout you'll come across 'extra' spaces, which are actually one space between every two elements.

There are workaround and solutions for this, other than resolving to floats:
- [Fighting the Space Between Inline Block Elements](http://css-tricks.com/fighting-the-space-between-inline-block-elements/)
- [Remove Whitespace Between Inline-Block Elements](http://davidwalsh.name/remove-whitespace-inline-block)

**Comment by zanona** [comment] 2014-03-28 12:08
Those are great tricks indeed. Inline-block is an excellent CSS Feature but their only drawback   would be this “extra" margin added. To be honest, I am not in favour of anything that changes the markup for adjusting styling issues on the page. But for those who don't care abou it, it is a great solution. Thanks for adding this to the list.

**Comment by mdo** [comment] 2014-03-28 15:56
Dupe of #1.

**Closed as completed by mdo** 2014-03-28 15:56 UTC
